import { readFile, writeFile } from "node:fs/promises";
import type { RouteInferenceResponse } from "../types.js";
import { loadEnv } from "../config/env.js";

async function readReceipt(path: string): Promise<RouteInferenceResponse> {
  return JSON.parse(await readFile(path, "utf8")) as RouteInferenceResponse;
}

function receiptSummary(receipt: RouteInferenceResponse): string {
  return [
    `- Status: \`${receipt.status}\``,
    `- Receipt: \`${receipt.receipt.receipt_path}\``,
    `- Prompt hash: \`${receipt.receipt.prompt_hash}\``,
    `- Quote ID: \`${receipt.receipt.quote_id}\``,
    `- Wallet policy: \`${receipt.wallet_policy.result}\`${receipt.wallet_policy.reason ? ` (${receipt.wallet_policy.reason})` : ""}`,
    `- Policy hash: \`${receipt.wallet_policy.policyHash}\``,
    `- Wallet reference: \`${receipt.wallet_policy.walletAddress || "missing"}\``,
    `- Selected provider: \`${receipt.broker_decision.selected_provider || "none"}\``,
    `- Payment status: \`${receipt.payment.status}\``,
    `- Operation ID: \`${receipt.payment.operation_id || "none"}\``,
    `- Payment reference: \`${receipt.payment.payment_reference || "none"}\``,
    `- Proof type: \`${receipt.payment.proof_type}\``,
    `- Provider request: \`${receipt.provider_invoice.provider_request_id || "none"}\``,
    `- Provider simulated: \`${receipt.provider_invoice.simulated}\``
  ].join("\n");
}

await loadEnv();

const approved = await readReceipt("receipts/coborouter_demo_approved_001.json");
const blocked = await readReceipt("receipts/coborouter_demo_blocked_001.json");

const warnings = [
  approved.provider_invoice.simulated
    ? "- Live provider proof missing: set `ZAI_API_KEY` and rerun `npm run demo:approved` before final submission."
    : "- Live provider proof present.",
  process.env.COBO_API_KEY && process.env.COBO_WALLET_ID
    ? "- Cobo credential env vars present."
    : "- Live Cobo credentials missing: current proof is generated by the Cobo-compatible demo adapter."
];

const report = `# Evidence Report — CoboRouter

Generated from the current local receipts.

## Blocked Path

${receiptSummary(blocked)}

Expected interpretation: Cobo policy blocked the attempted overspend. No authorization, payment, inference, or answer was created.

## Approved Path

${receiptSummary(approved)}

Expected interpretation: Cobo policy approved the spend, the broker selected the wallet-paid provider, inference completed, and a wallet-operation receipt was generated.

## Route Trace

### Blocked

\`\`\`json
${JSON.stringify(blocked.broker_decision.route_trace, null, 2)}
\`\`\`

### Approved

\`\`\`json
${JSON.stringify(approved.broker_decision.route_trace, null, 2)}
\`\`\`

## Live Submission Warnings

${warnings.join("\n")}

## Verification Commands

\`\`\`bash
npm run check
npm run smoke
npm run verify:submission
\`\`\`
`;

await writeFile("docs/EVIDENCE_REPORT.md", report, "utf8");
console.log("Wrote docs/EVIDENCE_REPORT.md");
